spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_acme_insurance
    username: user
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379

acme:
  insurance:
    cache-ttl-seconds:
      catalog-product: 3600
      catalog-offer: 3600

feign:
  catalog:
    product:
      api:
        baseurl: http://localhost:8081/products
    offer:
      api:
        baseurl: http://localhost:8081/offers

server:
  port: 8080
